<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of AnimusRedirect
 *
 * @author bbhask1x
 */
interface AnimusRedirect {
   /* Redirects can be of two types - Internal and External.
    * Internal redirections are done by generated by the framework. A class name, path and cause are required to trigger this kind of redirect.
    * External redirections are done by generating particular to the client browser. A location header and a cause are required to generate these types of redirections.
    */    
   function setRedirectType($REDIRECT_TYPE);  
   function setRedirectCause($REDIRECT_CAUSE);
   function setRedirectHeaderCode($REDIRECT_HEADER_CODE);
   function setRedirectLocation($REDIRECT_LOCATION);
}
